namespace Zoom_Server.Net.Codes;

public enum QstCode
{
    IS_CAMERAS_OF_USERS_STILL_ACTIVE,
    IS_MICROPHONES_OF_USERS_STILL_ACTIVE,
    IS_DEMONSTRATION_OF_USER_STILL_ACTIVE,
    IS_USERS_STILL_CONNECTED,

    //IS_MICROPHONES_OF_SINGLE_USER_STILL_ACTIVE,
    //IS_CAMERAS_OF_SINGLE_USER_STILL_ACTIVE,
    //IS_SINGLE_USER_STILL_CONNECTED,
}
