namespace Zoom_Server.Net.Codes;

public enum ScsCode
{
    NONE = 0,
    NAME_SUCCESSFULY_RENAMED,
    USER_SUCCESSFULY_CREATED,
    MEETING_SUCCESSFULY_CREATED,


    SCREEN_DEMONSTRATION_ALLOWED
}
